name: PR Build

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.13, 1.14, 1.15, 1.16, 1.17]
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        run: |
          go version
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.43.0
          golangci-lint --version

      - name: Run build
        run: |
          go build .

      - name: Run tests
        run: |
          go test -v
          golangci-lint run

      - name: Run linter
        run: |
          golangci-lint run
