name: Release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+

jobs:
  build:
    if: ${{ github.repository == 'Netflix/spectator-go' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.23, 1.24]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install Dependencies
        run: |
          sudo make install

      - name: Build
        run: |
          make build

      - name: Test
        run: |
          make test

      - name: Lint
        run: |
          make lint
