name: Snapshot

on:
  push:
    branches:
      - main

jobs:
  build:
    if: ${{ github.repository == 'Netflix/spectator-go' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.17, 1.18, 1.19]
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        run: |
          go version
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.50.1
          golangci-lint --version

      - name: Run build
        run: |
          go build .

      - name: Run tests
        run: |
          go test -v
          golangci-lint run

      - name: Run linter
        run: |
          golangci-lint run
