name: Snapshot

on:
  push:
    branches:
      - master

jobs:
  build:
    if: ${{ github.repository == 'Netflix/spectator-go' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.14, 1.15, 1.16, 1.17]
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint

      - name: Run build
        run: |
          go build .

      - name: Run tests
        run: |
          go test -v

      - name: Run vet & lint
        run: |
          go vet .
          golint .
